### PR TITLE
Seup files for app functionality

### PR DESCRIPTION
**Pull request by alexpuente0**
On this Pull request we:

- Setup file for a to-do app
- added functionality to checkboxes

### CODE REVIEW

**Review by jrosario19 — CHANGES_REQUESTED** [review]
## Hi @alexpuente0, 👋
You did a tremendous job so far! 💯 👏
**There are some issues that you still need to work on to go to the next project but you are almost there!** 💪
SoCloseSoCloseSethMeyersGIF

## Highlights ✅
✔️ Gitflow is used correctly
✔️ Code is clean

## Required Changes ♻️
- Kindly add the linters files to follow the coding guidelines for Microverse.
- The application works properly until you have developed it, but I encourage you to continue following the tutorial until you reach the final steps.

**Comment by alexpuente0** [comment]
@jrosario19 Thank you for the comments! can I request a new review? i updated the project

**Review by jrosario19 — APPROVED** [review]
## Status: Approved 🟢🟢🟢

Hi @alexpuente0 ,

Your project is complete! There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉

DonaldTrumpThumbsUpGIF


Highlight:
✅ Correct use of Github workflow
✅ No linter error
✅ README is professional
✅ Good descriptive PR
✅ App is working as expected 👍

Cheers and Happy coding!👏👏👏

**Comment by alexpuente0** [comment]
THank you @jrosario19

**Pull request merged**
